name: CICD
on: 
  workflow_dispatch: 
    inputs: 
      environment: 
        description: this is environment where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
           
jobs:
  code: 
    runs-on: ubuntu-latest 
    steps:
      - name: checkout code
        run: echo "code clone from GitHub"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "Testing the container"
  deploy:
    if: inputs.environment== 'dev'
    needs: [build, test]
    runs-on: ubuntu-latest 
    steps:
      - name: Deploying the app
        run: echo "Docker the compose deployed the app"
    
