name: CICD
on: 
  workflow_dispatch: 
  jobs:
   code: 
    runs-on: ubuntu-latest 
    steps:
      - name: checkout code
        run: echo "code clone from GitHub"
   build:
     runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"
   test:
     runs-on: ubuntu-latest
     steps:
       - name: test the container
         run: echo "Testing the container"
   deploy:
     runs-on: ubuntu-latest 
     steps:
       - name: Deploying the app
         run: echo "Docker the compose deployed the app"
    
